/* WARNING: This file is auto-generated by `west configen`. Do not modify manually. */

/*
 * Copyright (c) 2025 HARDWARIO a.s.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "app_config.h"

/* Zephyr includes */
#include <zephyr/init.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/settings/settings.h>
#include <zephyr/shell/shell.h>

/* Standard includes */
#include <ctype.h>
#include <errno.h>
#include <float.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

LOG_MODULE_REGISTER(app_config, LOG_LEVEL_DBG);

#define SETTINGS_PFX "config"

struct app_config g_app_config;

static const struct app_config m_app_config_defaults = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.lrw_sub_band = 2,
	.last_applied_region = APP_CONFIG_LRW_REGION_EU868,
	.alarm_temperature_lo = 15.0f,
	.alarm_temperature_hi = 25.0f,
	.alarm_temperature_hst = 0.5f,
	.alarm_humidity_lo = 30.0f,
	.alarm_humidity_hi = 75.0f,
	.alarm_humidity_hst = 5.0f,
	.alarm_pressure_lo = 700.0f,
	.alarm_pressure_hi = 1060.0f,
	.alarm_pressure_hst = 10.0f,
	.alarm_t1_temperature_lo = 15.0f,
	.alarm_t1_temperature_hi = 25.0f,
	.alarm_t1_temperature_hst = 0.5f,
	.alarm_t2_temperature_lo = 15.0f,
	.alarm_t2_temperature_hi = 25.0f,
	.alarm_t2_temperature_hst = 0.5f,
};

static struct app_config m_app_config = {
	.config_version = APP_CONFIG_VERSION,
	.interval_report = 900,
	.lrw_sub_band = 2,
	.last_applied_region = APP_CONFIG_LRW_REGION_EU868,
	.alarm_temperature_lo = 15.0f,
	.alarm_temperature_hi = 25.0f,
	.alarm_temperature_hst = 0.5f,
	.alarm_humidity_lo = 30.0f,
	.alarm_humidity_hi = 75.0f,
	.alarm_humidity_hst = 5.0f,
	.alarm_pressure_lo = 700.0f,
	.alarm_pressure_hi = 1060.0f,
	.alarm_pressure_hst = 10.0f,
	.alarm_t1_temperature_lo = 15.0f,
	.alarm_t1_temperature_hi = 25.0f,
	.alarm_t1_temperature_hst = 0.5f,
	.alarm_t2_temperature_lo = 15.0f,
	.alarm_t2_temperature_hi = 25.0f,
	.alarm_t2_temperature_hst = 0.5f,
};

static int h_set(const char *key, size_t len, settings_read_cb read_cb, void *cb_arg)
{
	int ret;
	const char *next;

#define SETTINGS_SET(_key, _var, _size)                                                            \
	do {                                                                                       \
		if (settings_name_steq(key, _key, &next) && !next) {                               \
			if (len != _size) {                                                        \
				return -EINVAL;                                                    \
			}                                                                          \
                                                                                                   \
			ret = read_cb(cb_arg, _var, len);                                          \
                                                                                                   \
			if (ret < 0) {                                                             \
				LOG_ERR("Call `read_cb` failed: %d", ret);                         \
				return ret;                                                        \
			}                                                                          \
                                                                                                   \
			return 0;                                                                  \
		}                                                                                  \
	} while (0)

	SETTINGS_SET("config-version", &m_app_config.config_version,
		     sizeof(m_app_config.config_version));
	SETTINGS_SET("secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
	SETTINGS_SET("serial-number", &m_app_config.serial_number,
		     sizeof(m_app_config.serial_number));
	SETTINGS_SET("nonce-counter", &m_app_config.nonce_counter,
		     sizeof(m_app_config.nonce_counter));
	SETTINGS_SET("calibration", &m_app_config.calibration,
		     sizeof(m_app_config.calibration));
	SETTINGS_SET("interval-sample", &m_app_config.interval_sample,
		     sizeof(m_app_config.interval_sample));
	SETTINGS_SET("interval-report", &m_app_config.interval_report,
		     sizeof(m_app_config.interval_report));
	SETTINGS_SET("lrw-region", &m_app_config.lrw_region,
		     sizeof(m_app_config.lrw_region));
	SETTINGS_SET("lrw-sub-band", &m_app_config.lrw_sub_band,
		     sizeof(m_app_config.lrw_sub_band));
	SETTINGS_SET("last-applied-region", &m_app_config.last_applied_region,
		     sizeof(m_app_config.last_applied_region));
	SETTINGS_SET("lrw-network", &m_app_config.lrw_network,
		     sizeof(m_app_config.lrw_network));
	SETTINGS_SET("lrw-adr", &m_app_config.lrw_adr,
		     sizeof(m_app_config.lrw_adr));
	SETTINGS_SET("lrw-activation", &m_app_config.lrw_activation,
		     sizeof(m_app_config.lrw_activation));
	SETTINGS_SET("lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	SETTINGS_SET("lrw-joineui", m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	SETTINGS_SET("lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	SETTINGS_SET("lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	SETTINGS_SET("lrw-devaddr", m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	SETTINGS_SET("lrw-nwkskey", m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	SETTINGS_SET("lrw-appskey", m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	SETTINGS_SET("alarm-temperature-enabled", &m_app_config.alarm_temperature_enabled,
		     sizeof(m_app_config.alarm_temperature_enabled));
	SETTINGS_SET("alarm-temperature-lo", &m_app_config.alarm_temperature_lo,
		     sizeof(m_app_config.alarm_temperature_lo));
	SETTINGS_SET("alarm-temperature-hi", &m_app_config.alarm_temperature_hi,
		     sizeof(m_app_config.alarm_temperature_hi));
	SETTINGS_SET("alarm-temperature-hst", &m_app_config.alarm_temperature_hst,
		     sizeof(m_app_config.alarm_temperature_hst));
	SETTINGS_SET("alarm-humidity-enabled", &m_app_config.alarm_humidity_enabled,
		     sizeof(m_app_config.alarm_humidity_enabled));
	SETTINGS_SET("alarm-humidity-lo", &m_app_config.alarm_humidity_lo,
		     sizeof(m_app_config.alarm_humidity_lo));
	SETTINGS_SET("alarm-humidity-hi", &m_app_config.alarm_humidity_hi,
		     sizeof(m_app_config.alarm_humidity_hi));
	SETTINGS_SET("alarm-humidity-hst", &m_app_config.alarm_humidity_hst,
		     sizeof(m_app_config.alarm_humidity_hst));
	SETTINGS_SET("alarm-pressure-enabled", &m_app_config.alarm_pressure_enabled,
		     sizeof(m_app_config.alarm_pressure_enabled));
	SETTINGS_SET("alarm-pressure-lo", &m_app_config.alarm_pressure_lo,
		     sizeof(m_app_config.alarm_pressure_lo));
	SETTINGS_SET("alarm-pressure-hi", &m_app_config.alarm_pressure_hi,
		     sizeof(m_app_config.alarm_pressure_hi));
	SETTINGS_SET("alarm-pressure-hst", &m_app_config.alarm_pressure_hst,
		     sizeof(m_app_config.alarm_pressure_hst));
	SETTINGS_SET("alarm-t1-temperature-enabled", &m_app_config.alarm_t1_temperature_enabled,
		     sizeof(m_app_config.alarm_t1_temperature_enabled));
	SETTINGS_SET("alarm-t1-temperature-lo", &m_app_config.alarm_t1_temperature_lo,
		     sizeof(m_app_config.alarm_t1_temperature_lo));
	SETTINGS_SET("alarm-t1-temperature-hi", &m_app_config.alarm_t1_temperature_hi,
		     sizeof(m_app_config.alarm_t1_temperature_hi));
	SETTINGS_SET("alarm-t1-temperature-hst", &m_app_config.alarm_t1_temperature_hst,
		     sizeof(m_app_config.alarm_t1_temperature_hst));
	SETTINGS_SET("alarm-t2-temperature-enabled", &m_app_config.alarm_t2_temperature_enabled,
		     sizeof(m_app_config.alarm_t2_temperature_enabled));
	SETTINGS_SET("alarm-t2-temperature-lo", &m_app_config.alarm_t2_temperature_lo,
		     sizeof(m_app_config.alarm_t2_temperature_lo));
	SETTINGS_SET("alarm-t2-temperature-hi", &m_app_config.alarm_t2_temperature_hi,
		     sizeof(m_app_config.alarm_t2_temperature_hi));
	SETTINGS_SET("alarm-t2-temperature-hst", &m_app_config.alarm_t2_temperature_hst,
		     sizeof(m_app_config.alarm_t2_temperature_hst));
	SETTINGS_SET("hall-left-counter", &m_app_config.hall_left_counter,
		     sizeof(m_app_config.hall_left_counter));
	SETTINGS_SET("hall-left-notify-act", &m_app_config.hall_left_notify_act,
		     sizeof(m_app_config.hall_left_notify_act));
	SETTINGS_SET("hall-left-notify-deact", &m_app_config.hall_left_notify_deact,
		     sizeof(m_app_config.hall_left_notify_deact));
	SETTINGS_SET("hall-right-counter", &m_app_config.hall_right_counter,
		     sizeof(m_app_config.hall_right_counter));
	SETTINGS_SET("hall-right-notify-act", &m_app_config.hall_right_notify_act,
		     sizeof(m_app_config.hall_right_notify_act));
	SETTINGS_SET("hall-right-notify-deact", &m_app_config.hall_right_notify_deact,
		     sizeof(m_app_config.hall_right_notify_deact));
	SETTINGS_SET("input-a-counter", &m_app_config.input_a_counter,
		     sizeof(m_app_config.input_a_counter));
	SETTINGS_SET("input-a-notify-act", &m_app_config.input_a_notify_act,
		     sizeof(m_app_config.input_a_notify_act));
	SETTINGS_SET("input-a-notify-deact", &m_app_config.input_a_notify_deact,
		     sizeof(m_app_config.input_a_notify_deact));
	SETTINGS_SET("input-b-counter", &m_app_config.input_b_counter,
		     sizeof(m_app_config.input_b_counter));
	SETTINGS_SET("input-b-notify-act", &m_app_config.input_b_notify_act,
		     sizeof(m_app_config.input_b_notify_act));
	SETTINGS_SET("input-b-notify-deact", &m_app_config.input_b_notify_deact,
		     sizeof(m_app_config.input_b_notify_deact));
	SETTINGS_SET("corr-temperature", &m_app_config.corr_temperature,
		     sizeof(m_app_config.corr_temperature));
	SETTINGS_SET("corr-t1-temperature", &m_app_config.corr_t1_temperature,
		     sizeof(m_app_config.corr_t1_temperature));
	SETTINGS_SET("corr-t2-temperature", &m_app_config.corr_t2_temperature,
		     sizeof(m_app_config.corr_t2_temperature));
	SETTINGS_SET("cap-hall-left", &m_app_config.cap_hall_left,
		     sizeof(m_app_config.cap_hall_left));
	SETTINGS_SET("cap-hall-right", &m_app_config.cap_hall_right,
		     sizeof(m_app_config.cap_hall_right));
	SETTINGS_SET("cap-input-a", &m_app_config.cap_input_a,
		     sizeof(m_app_config.cap_input_a));
	SETTINGS_SET("cap-input-b", &m_app_config.cap_input_b,
		     sizeof(m_app_config.cap_input_b));
	SETTINGS_SET("cap-light-sensor", &m_app_config.cap_light_sensor,
		     sizeof(m_app_config.cap_light_sensor));
	SETTINGS_SET("cap-barometer", &m_app_config.cap_barometer,
		     sizeof(m_app_config.cap_barometer));
	SETTINGS_SET("cap-pir-detector", &m_app_config.cap_pir_detector,
		     sizeof(m_app_config.cap_pir_detector));
	SETTINGS_SET("cap-1w-thermometer", &m_app_config.cap_1w_thermometer,
		     sizeof(m_app_config.cap_1w_thermometer));
	SETTINGS_SET("cap-1w-machine-probe", &m_app_config.cap_1w_machine_probe,
		     sizeof(m_app_config.cap_1w_machine_probe));

#undef SETTINGS_SET

	return -ENOENT;
}

static int h_commit(void)
{
	LOG_DBG("Loaded settings in full");

	if (m_app_config.config_version != APP_CONFIG_VERSION) {
		LOG_WRN("Config version mismatch (stored=%u, expected=%u), resetting to defaults",
			m_app_config.config_version, APP_CONFIG_VERSION);
		m_app_config = m_app_config_defaults;
	}

	memcpy(&g_app_config, &m_app_config, sizeof(g_app_config));
	return 0;
}

static int h_export(int (*export_func)(const char *name, const void *val, size_t val_len))
{
#define EXPORT_FUNC(_key, _var, _size)                                                             \
	do {                                                                                       \
		(void)export_func(SETTINGS_PFX "/" _key, _var, _size);                             \
	} while (0)

	EXPORT_FUNC("config-version", &m_app_config.config_version,
		    sizeof(m_app_config.config_version));
	EXPORT_FUNC("secret-key", m_app_config.secret_key, sizeof(m_app_config.secret_key));
	EXPORT_FUNC("serial-number", &m_app_config.serial_number,
		    sizeof(m_app_config.serial_number));
	EXPORT_FUNC("nonce-counter", &m_app_config.nonce_counter,
		    sizeof(m_app_config.nonce_counter));
	EXPORT_FUNC("calibration", &m_app_config.calibration,
		    sizeof(m_app_config.calibration));
	EXPORT_FUNC("interval-sample", &m_app_config.interval_sample,
		    sizeof(m_app_config.interval_sample));
	EXPORT_FUNC("interval-report", &m_app_config.interval_report,
		    sizeof(m_app_config.interval_report));
	EXPORT_FUNC("lrw-region", &m_app_config.lrw_region,
		    sizeof(m_app_config.lrw_region));
	EXPORT_FUNC("lrw-sub-band", &m_app_config.lrw_sub_band,
		    sizeof(m_app_config.lrw_sub_band));
	EXPORT_FUNC("last-applied-region", &m_app_config.last_applied_region,
		    sizeof(m_app_config.last_applied_region));
	EXPORT_FUNC("lrw-network", &m_app_config.lrw_network,
		    sizeof(m_app_config.lrw_network));
	EXPORT_FUNC("lrw-adr", &m_app_config.lrw_adr,
		    sizeof(m_app_config.lrw_adr));
	EXPORT_FUNC("lrw-activation", &m_app_config.lrw_activation,
		    sizeof(m_app_config.lrw_activation));
	EXPORT_FUNC("lrw-deveui", m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui));
	EXPORT_FUNC("lrw-joineui", m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui));
	EXPORT_FUNC("lrw-nwkkey", m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey));
	EXPORT_FUNC("lrw-appkey", m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey));
	EXPORT_FUNC("lrw-devaddr", m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr));
	EXPORT_FUNC("lrw-nwkskey", m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey));
	EXPORT_FUNC("lrw-appskey", m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey));
	EXPORT_FUNC("alarm-temperature-enabled", &m_app_config.alarm_temperature_enabled,
		    sizeof(m_app_config.alarm_temperature_enabled));
	EXPORT_FUNC("alarm-temperature-lo", &m_app_config.alarm_temperature_lo,
		    sizeof(m_app_config.alarm_temperature_lo));
	EXPORT_FUNC("alarm-temperature-hi", &m_app_config.alarm_temperature_hi,
		    sizeof(m_app_config.alarm_temperature_hi));
	EXPORT_FUNC("alarm-temperature-hst", &m_app_config.alarm_temperature_hst,
		    sizeof(m_app_config.alarm_temperature_hst));
	EXPORT_FUNC("alarm-humidity-enabled", &m_app_config.alarm_humidity_enabled,
		    sizeof(m_app_config.alarm_humidity_enabled));
	EXPORT_FUNC("alarm-humidity-lo", &m_app_config.alarm_humidity_lo,
		    sizeof(m_app_config.alarm_humidity_lo));
	EXPORT_FUNC("alarm-humidity-hi", &m_app_config.alarm_humidity_hi,
		    sizeof(m_app_config.alarm_humidity_hi));
	EXPORT_FUNC("alarm-humidity-hst", &m_app_config.alarm_humidity_hst,
		    sizeof(m_app_config.alarm_humidity_hst));
	EXPORT_FUNC("alarm-pressure-enabled", &m_app_config.alarm_pressure_enabled,
		    sizeof(m_app_config.alarm_pressure_enabled));
	EXPORT_FUNC("alarm-pressure-lo", &m_app_config.alarm_pressure_lo,
		    sizeof(m_app_config.alarm_pressure_lo));
	EXPORT_FUNC("alarm-pressure-hi", &m_app_config.alarm_pressure_hi,
		    sizeof(m_app_config.alarm_pressure_hi));
	EXPORT_FUNC("alarm-pressure-hst", &m_app_config.alarm_pressure_hst,
		    sizeof(m_app_config.alarm_pressure_hst));
	EXPORT_FUNC("alarm-t1-temperature-enabled", &m_app_config.alarm_t1_temperature_enabled,
		    sizeof(m_app_config.alarm_t1_temperature_enabled));
	EXPORT_FUNC("alarm-t1-temperature-lo", &m_app_config.alarm_t1_temperature_lo,
		    sizeof(m_app_config.alarm_t1_temperature_lo));
	EXPORT_FUNC("alarm-t1-temperature-hi", &m_app_config.alarm_t1_temperature_hi,
		    sizeof(m_app_config.alarm_t1_temperature_hi));
	EXPORT_FUNC("alarm-t1-temperature-hst", &m_app_config.alarm_t1_temperature_hst,
		    sizeof(m_app_config.alarm_t1_temperature_hst));
	EXPORT_FUNC("alarm-t2-temperature-enabled", &m_app_config.alarm_t2_temperature_enabled,
		    sizeof(m_app_config.alarm_t2_temperature_enabled));
	EXPORT_FUNC("alarm-t2-temperature-lo", &m_app_config.alarm_t2_temperature_lo,
		    sizeof(m_app_config.alarm_t2_temperature_lo));
	EXPORT_FUNC("alarm-t2-temperature-hi", &m_app_config.alarm_t2_temperature_hi,
		    sizeof(m_app_config.alarm_t2_temperature_hi));
	EXPORT_FUNC("alarm-t2-temperature-hst", &m_app_config.alarm_t2_temperature_hst,
		    sizeof(m_app_config.alarm_t2_temperature_hst));
	EXPORT_FUNC("hall-left-counter", &m_app_config.hall_left_counter,
		    sizeof(m_app_config.hall_left_counter));
	EXPORT_FUNC("hall-left-notify-act", &m_app_config.hall_left_notify_act,
		    sizeof(m_app_config.hall_left_notify_act));
	EXPORT_FUNC("hall-left-notify-deact", &m_app_config.hall_left_notify_deact,
		    sizeof(m_app_config.hall_left_notify_deact));
	EXPORT_FUNC("hall-right-counter", &m_app_config.hall_right_counter,
		    sizeof(m_app_config.hall_right_counter));
	EXPORT_FUNC("hall-right-notify-act", &m_app_config.hall_right_notify_act,
		    sizeof(m_app_config.hall_right_notify_act));
	EXPORT_FUNC("hall-right-notify-deact", &m_app_config.hall_right_notify_deact,
		    sizeof(m_app_config.hall_right_notify_deact));
	EXPORT_FUNC("input-a-counter", &m_app_config.input_a_counter,
		    sizeof(m_app_config.input_a_counter));
	EXPORT_FUNC("input-a-notify-act", &m_app_config.input_a_notify_act,
		    sizeof(m_app_config.input_a_notify_act));
	EXPORT_FUNC("input-a-notify-deact", &m_app_config.input_a_notify_deact,
		    sizeof(m_app_config.input_a_notify_deact));
	EXPORT_FUNC("input-b-counter", &m_app_config.input_b_counter,
		    sizeof(m_app_config.input_b_counter));
	EXPORT_FUNC("input-b-notify-act", &m_app_config.input_b_notify_act,
		    sizeof(m_app_config.input_b_notify_act));
	EXPORT_FUNC("input-b-notify-deact", &m_app_config.input_b_notify_deact,
		    sizeof(m_app_config.input_b_notify_deact));
	EXPORT_FUNC("corr-temperature", &m_app_config.corr_temperature,
		    sizeof(m_app_config.corr_temperature));
	EXPORT_FUNC("corr-t1-temperature", &m_app_config.corr_t1_temperature,
		    sizeof(m_app_config.corr_t1_temperature));
	EXPORT_FUNC("corr-t2-temperature", &m_app_config.corr_t2_temperature,
		    sizeof(m_app_config.corr_t2_temperature));
	EXPORT_FUNC("cap-hall-left", &m_app_config.cap_hall_left,
		    sizeof(m_app_config.cap_hall_left));
	EXPORT_FUNC("cap-hall-right", &m_app_config.cap_hall_right,
		    sizeof(m_app_config.cap_hall_right));
	EXPORT_FUNC("cap-input-a", &m_app_config.cap_input_a,
		    sizeof(m_app_config.cap_input_a));
	EXPORT_FUNC("cap-input-b", &m_app_config.cap_input_b,
		    sizeof(m_app_config.cap_input_b));
	EXPORT_FUNC("cap-light-sensor", &m_app_config.cap_light_sensor,
		    sizeof(m_app_config.cap_light_sensor));
	EXPORT_FUNC("cap-barometer", &m_app_config.cap_barometer,
		    sizeof(m_app_config.cap_barometer));
	EXPORT_FUNC("cap-pir-detector", &m_app_config.cap_pir_detector,
		    sizeof(m_app_config.cap_pir_detector));
	EXPORT_FUNC("cap-1w-thermometer", &m_app_config.cap_1w_thermometer,
		    sizeof(m_app_config.cap_1w_thermometer));
	EXPORT_FUNC("cap-1w-machine-probe", &m_app_config.cap_1w_machine_probe,
		    sizeof(m_app_config.cap_1w_machine_probe));

#undef EXPORT_FUNC

	return 0;
}

#if defined(CONFIG_SHELL)

static const char m_msg_invalid_args[] = "invalid number of arguments";
static const char m_msg_invalid_range[] = "invalid argument range";
static const char m_msg_invalid_value[] = "invalid argument value";
static const char m_msg_cmd_success[] = "command succeeded";

typedef void (*print_func_t)(const struct shell *shell);

static int cmd_bool(const struct shell *shell, size_t argc, char **argv, bool *param,
		    print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (!strcmp(argv[1], "true")) {
		*param = true;
	} else if (!strcmp(argv[1], "false")) {
		*param = false;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_int(const struct shell *shell, size_t argc, char **argv, int *param, int min,
		   int max, print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	long value = strtol(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (value < min || value > max) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	*param = (int)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_float(const struct shell *shell, size_t argc, char **argv, float *param,
		     float min, float max, print_func_t print_func)
{
	if (argc == 1) {
		if (print_func) {
			print_func(shell);
		}
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	float value = strtof(argv[1], &endptr);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (value < min || value > max) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	*param = value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}


static void print_secret_key(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.secret_key) + 1];

	int ret =
		bin2hex(m_app_config.secret_key, sizeof(m_app_config.secret_key), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " secret-key %s", buf);
}

static void print_serial_number(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " serial-number %010u", m_app_config.serial_number);
}

static void print_nonce_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " nonce-counter %u", m_app_config.nonce_counter);
}

static void print_calibration(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " calibration %s",
		    m_app_config.calibration ? "true" : "false");
}

static void print_interval_sample(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " interval-sample %d", m_app_config.interval_sample);
}

static void print_interval_report(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " interval-report %d", m_app_config.interval_report);
}

static void print_lrw_region(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_region) {
	case APP_CONFIG_LRW_REGION_EU868:
		str = "eu868";
		break;
	case APP_CONFIG_LRW_REGION_US915:
		str = "us915";
		break;
	case APP_CONFIG_LRW_REGION_AU915:
		str = "au915";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-region %s", str);
}

static void print_lrw_sub_band(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-sub-band %d", m_app_config.lrw_sub_band);
}

static void print_last_applied_region(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.last_applied_region) {
	case APP_CONFIG_LRW_REGION_EU868:
		str = "eu868";
		break;
	case APP_CONFIG_LRW_REGION_US915:
		str = "us915";
		break;
	case APP_CONFIG_LRW_REGION_AU915:
		str = "au915";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " last-applied-region %s", str);
}

static void print_lrw_network(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_network) {
	case APP_CONFIG_LRW_NETWORK_PUBLIC:
		str = "public";
		break;
	case APP_CONFIG_LRW_NETWORK_PRIVATE:
		str = "private";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-network %s", str);
}

static void print_lrw_adr(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " lrw-adr %s",
		    m_app_config.lrw_adr ? "true" : "false");
}

static void print_lrw_activation(const struct shell *shell)
{
	const char *str;
	switch (m_app_config.lrw_activation) {
	case APP_CONFIG_LRW_ACTIVATION_OTAA:
		str = "otaa";
		break;
	case APP_CONFIG_LRW_ACTIVATION_ABP:
		str = "abp";
		break;
	default:
		str = "unknown";
		break;
	}
	shell_print(shell, SETTINGS_PFX " lrw-activation %s", str);
}

static void print_lrw_deveui(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_deveui) + 1];

	int ret =
		bin2hex(m_app_config.lrw_deveui, sizeof(m_app_config.lrw_deveui), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-deveui %s", buf);
}

static void print_lrw_joineui(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_joineui) + 1];

	int ret =
		bin2hex(m_app_config.lrw_joineui, sizeof(m_app_config.lrw_joineui), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-joineui %s", buf);
}

static void print_lrw_nwkkey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_nwkkey) + 1];

	int ret =
		bin2hex(m_app_config.lrw_nwkkey, sizeof(m_app_config.lrw_nwkkey), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-nwkkey %s", buf);
}

static void print_lrw_appkey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_appkey) + 1];

	int ret =
		bin2hex(m_app_config.lrw_appkey, sizeof(m_app_config.lrw_appkey), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-appkey %s", buf);
}

static void print_lrw_devaddr(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_devaddr) + 1];

	int ret =
		bin2hex(m_app_config.lrw_devaddr, sizeof(m_app_config.lrw_devaddr), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-devaddr %s", buf);
}

static void print_lrw_nwkskey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_nwkskey) + 1];

	int ret =
		bin2hex(m_app_config.lrw_nwkskey, sizeof(m_app_config.lrw_nwkskey), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-nwkskey %s", buf);
}

static void print_lrw_appskey(const struct shell *shell)
{
	char buf[2 * sizeof(m_app_config.lrw_appskey) + 1];

	int ret =
		bin2hex(m_app_config.lrw_appskey, sizeof(m_app_config.lrw_appskey), buf, sizeof(buf));
	if (!ret) {
		LOG_ERR("Call `bin2hex` failed: %d", ret);
		return;
	}

	shell_print(shell, SETTINGS_PFX " lrw-appskey %s", buf);
}

static void print_alarm_temperature_enabled(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-temperature-enabled %s",
		    m_app_config.alarm_temperature_enabled ? "true" : "false");
}

static void print_alarm_temperature_lo(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-temperature-lo %.2f",
		    (double)m_app_config.alarm_temperature_lo);
}

static void print_alarm_temperature_hi(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-temperature-hi %.2f",
		    (double)m_app_config.alarm_temperature_hi);
}

static void print_alarm_temperature_hst(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-temperature-hst %.2f",
		    (double)m_app_config.alarm_temperature_hst);
}

static void print_alarm_humidity_enabled(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-humidity-enabled %s",
		    m_app_config.alarm_humidity_enabled ? "true" : "false");
}

static void print_alarm_humidity_lo(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-humidity-lo %.2f",
		    (double)m_app_config.alarm_humidity_lo);
}

static void print_alarm_humidity_hi(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-humidity-hi %.2f",
		    (double)m_app_config.alarm_humidity_hi);
}

static void print_alarm_humidity_hst(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-humidity-hst %.2f",
		    (double)m_app_config.alarm_humidity_hst);
}

static void print_alarm_pressure_enabled(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-pressure-enabled %s",
		    m_app_config.alarm_pressure_enabled ? "true" : "false");
}

static void print_alarm_pressure_lo(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-pressure-lo %.2f",
		    (double)m_app_config.alarm_pressure_lo);
}

static void print_alarm_pressure_hi(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-pressure-hi %.2f",
		    (double)m_app_config.alarm_pressure_hi);
}

static void print_alarm_pressure_hst(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-pressure-hst %.2f",
		    (double)m_app_config.alarm_pressure_hst);
}

static void print_alarm_t1_temperature_enabled(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t1-temperature-enabled %s",
		    m_app_config.alarm_t1_temperature_enabled ? "true" : "false");
}

static void print_alarm_t1_temperature_lo(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t1-temperature-lo %.2f",
		    (double)m_app_config.alarm_t1_temperature_lo);
}

static void print_alarm_t1_temperature_hi(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t1-temperature-hi %.2f",
		    (double)m_app_config.alarm_t1_temperature_hi);
}

static void print_alarm_t1_temperature_hst(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t1-temperature-hst %.2f",
		    (double)m_app_config.alarm_t1_temperature_hst);
}

static void print_alarm_t2_temperature_enabled(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t2-temperature-enabled %s",
		    m_app_config.alarm_t2_temperature_enabled ? "true" : "false");
}

static void print_alarm_t2_temperature_lo(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t2-temperature-lo %.2f",
		    (double)m_app_config.alarm_t2_temperature_lo);
}

static void print_alarm_t2_temperature_hi(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t2-temperature-hi %.2f",
		    (double)m_app_config.alarm_t2_temperature_hi);
}

static void print_alarm_t2_temperature_hst(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " alarm-t2-temperature-hst %.2f",
		    (double)m_app_config.alarm_t2_temperature_hst);
}

static void print_hall_left_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-left-counter %s",
		    m_app_config.hall_left_counter ? "true" : "false");
}

static void print_hall_left_notify_act(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-left-notify-act %s",
		    m_app_config.hall_left_notify_act ? "true" : "false");
}

static void print_hall_left_notify_deact(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-left-notify-deact %s",
		    m_app_config.hall_left_notify_deact ? "true" : "false");
}

static void print_hall_right_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-right-counter %s",
		    m_app_config.hall_right_counter ? "true" : "false");
}

static void print_hall_right_notify_act(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-right-notify-act %s",
		    m_app_config.hall_right_notify_act ? "true" : "false");
}

static void print_hall_right_notify_deact(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " hall-right-notify-deact %s",
		    m_app_config.hall_right_notify_deact ? "true" : "false");
}

static void print_input_a_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-a-counter %s",
		    m_app_config.input_a_counter ? "true" : "false");
}

static void print_input_a_notify_act(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-a-notify-act %s",
		    m_app_config.input_a_notify_act ? "true" : "false");
}

static void print_input_a_notify_deact(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-a-notify-deact %s",
		    m_app_config.input_a_notify_deact ? "true" : "false");
}

static void print_input_b_counter(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-b-counter %s",
		    m_app_config.input_b_counter ? "true" : "false");
}

static void print_input_b_notify_act(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-b-notify-act %s",
		    m_app_config.input_b_notify_act ? "true" : "false");
}

static void print_input_b_notify_deact(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " input-b-notify-deact %s",
		    m_app_config.input_b_notify_deact ? "true" : "false");
}

static void print_corr_temperature(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " corr-temperature %.2f",
		    (double)m_app_config.corr_temperature);
}

static void print_corr_t1_temperature(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " corr-t1-temperature %.2f",
		    (double)m_app_config.corr_t1_temperature);
}

static void print_corr_t2_temperature(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " corr-t2-temperature %.2f",
		    (double)m_app_config.corr_t2_temperature);
}

static void print_cap_hall_left(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-hall-left %s",
		    m_app_config.cap_hall_left ? "true" : "false");
}

static void print_cap_hall_right(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-hall-right %s",
		    m_app_config.cap_hall_right ? "true" : "false");
}

static void print_cap_input_a(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-input-a %s",
		    m_app_config.cap_input_a ? "true" : "false");
}

static void print_cap_input_b(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-input-b %s",
		    m_app_config.cap_input_b ? "true" : "false");
}

static void print_cap_light_sensor(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-light-sensor %s",
		    m_app_config.cap_light_sensor ? "true" : "false");
}

static void print_cap_barometer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-barometer %s",
		    m_app_config.cap_barometer ? "true" : "false");
}

static void print_cap_pir_detector(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-pir-detector %s",
		    m_app_config.cap_pir_detector ? "true" : "false");
}

static void print_cap_1w_thermometer(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-1w-thermometer %s",
		    m_app_config.cap_1w_thermometer ? "true" : "false");
}

static void print_cap_1w_machine_probe(const struct shell *shell)
{
	shell_print(shell, SETTINGS_PFX " cap-1w-machine-probe %s",
		    m_app_config.cap_1w_machine_probe ? "true" : "false");
}

static int cmd_show(const struct shell *shell, size_t argc, char **argv)
{
	print_secret_key(shell);
	print_serial_number(shell);
	print_nonce_counter(shell);
	print_calibration(shell);
	print_interval_sample(shell);
	print_interval_report(shell);
	print_lrw_region(shell);
	print_lrw_sub_band(shell);
	print_lrw_network(shell);
	print_lrw_adr(shell);
	print_lrw_activation(shell);
	print_lrw_deveui(shell);
	print_lrw_joineui(shell);
	print_lrw_nwkkey(shell);
	print_lrw_appkey(shell);
	print_lrw_devaddr(shell);
	print_lrw_nwkskey(shell);
	print_lrw_appskey(shell);
	print_alarm_temperature_enabled(shell);
	print_alarm_temperature_lo(shell);
	print_alarm_temperature_hi(shell);
	print_alarm_temperature_hst(shell);
	print_alarm_humidity_enabled(shell);
	print_alarm_humidity_lo(shell);
	print_alarm_humidity_hi(shell);
	print_alarm_humidity_hst(shell);
	print_alarm_pressure_enabled(shell);
	print_alarm_pressure_lo(shell);
	print_alarm_pressure_hi(shell);
	print_alarm_pressure_hst(shell);
	print_alarm_t1_temperature_enabled(shell);
	print_alarm_t1_temperature_lo(shell);
	print_alarm_t1_temperature_hi(shell);
	print_alarm_t1_temperature_hst(shell);
	print_alarm_t2_temperature_enabled(shell);
	print_alarm_t2_temperature_lo(shell);
	print_alarm_t2_temperature_hi(shell);
	print_alarm_t2_temperature_hst(shell);
	print_hall_left_counter(shell);
	print_hall_left_notify_act(shell);
	print_hall_left_notify_deact(shell);
	print_hall_right_counter(shell);
	print_hall_right_notify_act(shell);
	print_hall_right_notify_deact(shell);
	print_input_a_counter(shell);
	print_input_a_notify_act(shell);
	print_input_a_notify_deact(shell);
	print_input_b_counter(shell);
	print_input_b_notify_act(shell);
	print_input_b_notify_deact(shell);
	print_corr_temperature(shell);
	print_corr_t1_temperature(shell);
	print_corr_t2_temperature(shell);
	print_cap_hall_left(shell);
	print_cap_hall_right(shell);
	print_cap_input_a(shell);
	print_cap_input_b(shell);
	print_cap_light_sensor(shell);
	print_cap_barometer(shell);
	print_cap_pir_detector(shell);
	print_cap_1w_thermometer(shell);
	print_cap_1w_machine_probe(shell);

	return 0;
}

static int cmd_secret_key(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_secret_key(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.secret_key)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.secret_key,
		      sizeof(m_app_config.secret_key));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_serial_number(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_serial_number(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	size_t len = strlen(argv[1]);

	if (len != 10) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	for (size_t i = 0; i < len; i++) {
		if (!isdigit((int)argv[1][i])) {
			shell_error(shell, "%s", m_msg_invalid_value);
			return -EINVAL;
		}
	}

	m_app_config.serial_number = strtoul(argv[1], NULL, 10);

	return 0;
}

static int cmd_nonce_counter(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_nonce_counter(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	char *endptr;
	unsigned long value = strtoul(argv[1], &endptr, 10);

	if (*endptr != '\0' || endptr == argv[1]) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	if (value < 0 || value > UINT32_MAX) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.nonce_counter = (uint32_t)value;
	shell_print(shell, "%s", m_msg_cmd_success);
	return 0;
}

static int cmd_calibration(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.calibration, print_calibration);
}

static int cmd_interval_sample(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_interval_sample(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	int a = strtol(argv[1], NULL, 10);

	if (a != 0 && (a < 5 || a > 3600)) {
		shell_error(shell, "%s", m_msg_invalid_range);
		return -EINVAL;
	}

	m_app_config.interval_sample = a;

	return 0;
}

static int cmd_interval_report(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.interval_report, 60, 86400,
		       print_interval_report);
}

static int cmd_lrw_region(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_region(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (!strcmp(argv[1], "eu868")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_EU868;
	} else if (!strcmp(argv[1], "us915")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_US915;
	} else if (!strcmp(argv[1], "au915")) {
		m_app_config.lrw_region = APP_CONFIG_LRW_REGION_AU915;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_sub_band(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_int(shell, argc, argv, &m_app_config.lrw_sub_band, 0, 8,
		       print_lrw_sub_band);
}

static int cmd_last_applied_region(const struct shell *shell, size_t argc, char **argv)
{
	print_last_applied_region(shell);
	return 0;
}

static int cmd_lrw_network(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_network(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (!strcmp(argv[1], "public")) {
		m_app_config.lrw_network = APP_CONFIG_LRW_NETWORK_PUBLIC;
	} else if (!strcmp(argv[1], "private")) {
		m_app_config.lrw_network = APP_CONFIG_LRW_NETWORK_PRIVATE;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_adr(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.lrw_adr, print_lrw_adr);
}

static int cmd_lrw_activation(const struct shell *shell, size_t argc, char **argv)
{
	if (argc == 1) {
		print_lrw_activation(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (!strcmp(argv[1], "otaa")) {
		m_app_config.lrw_activation = APP_CONFIG_LRW_ACTIVATION_OTAA;
	} else if (!strcmp(argv[1], "abp")) {
		m_app_config.lrw_activation = APP_CONFIG_LRW_ACTIVATION_ABP;
	} else {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	return 0;
}

static int cmd_lrw_deveui(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_deveui(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_deveui)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_deveui,
		      sizeof(m_app_config.lrw_deveui));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_lrw_joineui(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_joineui(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_joineui)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_joineui,
		      sizeof(m_app_config.lrw_joineui));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_lrw_nwkkey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_nwkkey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_nwkkey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_nwkkey,
		      sizeof(m_app_config.lrw_nwkkey));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_lrw_appkey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_appkey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_appkey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_appkey,
		      sizeof(m_app_config.lrw_appkey));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_lrw_devaddr(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_devaddr(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_devaddr)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_devaddr,
		      sizeof(m_app_config.lrw_devaddr));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_lrw_nwkskey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_nwkskey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_nwkskey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_nwkskey,
		      sizeof(m_app_config.lrw_nwkskey));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_lrw_appskey(const struct shell *shell, size_t argc, char **argv)
{
	int ret;

	if (argc == 1) {
		print_lrw_appskey(shell);
		return 0;
	}

	if (argc != 2) {
		shell_error(shell, "%s", m_msg_invalid_args);
		return -EINVAL;
	}

	if (strlen(argv[1]) != 2 * sizeof(m_app_config.lrw_appskey)) {
		shell_error(shell, "%s", m_msg_invalid_value);
		return -EINVAL;
	}

	ret = hex2bin(argv[1], strlen(argv[1]), m_app_config.lrw_appskey,
		      sizeof(m_app_config.lrw_appskey));
	if (!ret) {
		LOG_ERR("Call `hex2bin` failed: %d", ret);
		shell_error(shell, "%s", m_msg_invalid_value);
		return ret;
	}

	return 0;
}

static int cmd_alarm_temperature_enabled(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.alarm_temperature_enabled, print_alarm_temperature_enabled);
}

static int cmd_alarm_temperature_lo(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_temperature_lo, -30.0f,
			 70.0f, print_alarm_temperature_lo);
}

static int cmd_alarm_temperature_hi(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_temperature_hi, -30.0f,
			 70.0f, print_alarm_temperature_hi);
}

static int cmd_alarm_temperature_hst(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_temperature_hst, 0.0f,
			 5.0f, print_alarm_temperature_hst);
}

static int cmd_alarm_humidity_enabled(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.alarm_humidity_enabled, print_alarm_humidity_enabled);
}

static int cmd_alarm_humidity_lo(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_humidity_lo, 0.0f,
			 100.0f, print_alarm_humidity_lo);
}

static int cmd_alarm_humidity_hi(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_humidity_hi, 0.0f,
			 100.0f, print_alarm_humidity_hi);
}

static int cmd_alarm_humidity_hst(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_humidity_hst, 0.0f,
			 20.0f, print_alarm_humidity_hst);
}

static int cmd_alarm_pressure_enabled(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.alarm_pressure_enabled, print_alarm_pressure_enabled);
}

static int cmd_alarm_pressure_lo(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_pressure_lo, 500.0f,
			 1200.0f, print_alarm_pressure_lo);
}

static int cmd_alarm_pressure_hi(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_pressure_hi, 500.0f,
			 1200.0f, print_alarm_pressure_hi);
}

static int cmd_alarm_pressure_hst(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_pressure_hst, 0.0f,
			 50.0f, print_alarm_pressure_hst);
}

static int cmd_alarm_t1_temperature_enabled(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.alarm_t1_temperature_enabled, print_alarm_t1_temperature_enabled);
}

static int cmd_alarm_t1_temperature_lo(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_t1_temperature_lo, -30.0f,
			 70.0f, print_alarm_t1_temperature_lo);
}

static int cmd_alarm_t1_temperature_hi(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_t1_temperature_hi, -30.0f,
			 70.0f, print_alarm_t1_temperature_hi);
}

static int cmd_alarm_t1_temperature_hst(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_t1_temperature_hst, 0.0f,
			 5.0f, print_alarm_t1_temperature_hst);
}

static int cmd_alarm_t2_temperature_enabled(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.alarm_t2_temperature_enabled, print_alarm_t2_temperature_enabled);
}

static int cmd_alarm_t2_temperature_lo(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_t2_temperature_lo, -30.0f,
			 70.0f, print_alarm_t2_temperature_lo);
}

static int cmd_alarm_t2_temperature_hi(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_t2_temperature_hi, -30.0f,
			 70.0f, print_alarm_t2_temperature_hi);
}

static int cmd_alarm_t2_temperature_hst(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.alarm_t2_temperature_hst, 0.0f,
			 5.0f, print_alarm_t2_temperature_hst);
}

static int cmd_hall_left_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_left_counter, print_hall_left_counter);
}

static int cmd_hall_left_notify_act(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_left_notify_act, print_hall_left_notify_act);
}

static int cmd_hall_left_notify_deact(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_left_notify_deact, print_hall_left_notify_deact);
}

static int cmd_hall_right_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_right_counter, print_hall_right_counter);
}

static int cmd_hall_right_notify_act(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_right_notify_act, print_hall_right_notify_act);
}

static int cmd_hall_right_notify_deact(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.hall_right_notify_deact, print_hall_right_notify_deact);
}

static int cmd_input_a_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_a_counter, print_input_a_counter);
}

static int cmd_input_a_notify_act(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_a_notify_act, print_input_a_notify_act);
}

static int cmd_input_a_notify_deact(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_a_notify_deact, print_input_a_notify_deact);
}

static int cmd_input_b_counter(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_b_counter, print_input_b_counter);
}

static int cmd_input_b_notify_act(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_b_notify_act, print_input_b_notify_act);
}

static int cmd_input_b_notify_deact(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.input_b_notify_deact, print_input_b_notify_deact);
}

static int cmd_corr_temperature(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.corr_temperature, -5.0f,
			 5.0f, print_corr_temperature);
}

static int cmd_corr_t1_temperature(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.corr_t1_temperature, -5.0f,
			 5.0f, print_corr_t1_temperature);
}

static int cmd_corr_t2_temperature(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_float(shell, argc, argv, &m_app_config.corr_t2_temperature, -5.0f,
			 5.0f, print_corr_t2_temperature);
}

static int cmd_cap_hall_left(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_hall_left, print_cap_hall_left);
}

static int cmd_cap_hall_right(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_hall_right, print_cap_hall_right);
}

static int cmd_cap_input_a(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_input_a, print_cap_input_a);
}

static int cmd_cap_input_b(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_input_b, print_cap_input_b);
}

static int cmd_cap_light_sensor(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_light_sensor, print_cap_light_sensor);
}

static int cmd_cap_barometer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_barometer, print_cap_barometer);
}

static int cmd_cap_pir_detector(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_pir_detector, print_cap_pir_detector);
}

static int cmd_cap_1w_thermometer(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_1w_thermometer, print_cap_1w_thermometer);
}

static int cmd_cap_1w_machine_probe(const struct shell *shell, size_t argc, char **argv)
{
	return cmd_bool(shell, argc, argv, &m_app_config.cap_1w_machine_probe, print_cap_1w_machine_probe);
}

static int print_help(const struct shell *shell, size_t argc, char **argv)
{
	if (argc > 1) {
		shell_error(shell, "command not found: %s", argv[1]);
		shell_help(shell);
		return -EINVAL;
	}

	shell_help(shell);

	return 0;
}

/* clang-format off */

SHELL_STATIC_SUBCMD_SET_CREATE(
	sub_config,

	SHELL_CMD_ARG(show, NULL,
	              "Show all configuration.",
	              cmd_show, 1, 0),

	SHELL_CMD_ARG(secret-key, NULL,
	              "Get/Set device secret key (32 hexadecimal digits).",
	              cmd_secret_key, 1, 1),

	SHELL_CMD_ARG(serial-number, NULL,
	              "Get/Set device serial number (10 decimal digits).",
	              cmd_serial_number, 1, 1),

	SHELL_CMD_ARG(nonce-counter, NULL,
	              "Get/Set nonce counter (unsigned integer).",
	              cmd_nonce_counter, 1, 1),

	SHELL_CMD_ARG(calibration, NULL,
	              "Get/Set calibration mode (true/false).",
	              cmd_calibration, 1, 1),

	SHELL_CMD_ARG(interval-sample, NULL,
	              "Get/Set sample interval (range 5 to 3600 seconds; 0 = precede report).",
	              cmd_interval_sample, 1, 1),

	SHELL_CMD_ARG(interval-report, NULL,
	              "Get/Set report interval (range 60 to 86400 seconds).",
	              cmd_interval_report, 1, 1),

	SHELL_CMD_ARG(lrw-region, NULL,
	              "Get/Set LoRaWAN region (eu868/us915/au915).",
	              cmd_lrw_region, 1, 1),

	SHELL_CMD_ARG(lrw-sub-band, NULL,
	              "Get/Set US915/AU915 sub-band (1-8, 0 = all channels). Default 2 matches TTN/Helium/ChirpStack.",
	              cmd_lrw_sub_band, 1, 1),

	SHELL_CMD_ARG(last-applied-region, NULL,
	              "Internal - last region applied to LoRaWAN NVM. Maintained by app_lrw.",
	              cmd_last_applied_region, 1, 1),

	SHELL_CMD_ARG(lrw-network, NULL,
	              "Get/Set LoRaWAN network (public/private).",
	              cmd_lrw_network, 1, 1),

	SHELL_CMD_ARG(lrw-adr, NULL,
	              "Get/Set LoRaWAN ADR (true/false).",
	              cmd_lrw_adr, 1, 1),

	SHELL_CMD_ARG(lrw-activation, NULL,
	              "Get/Set LoRaWAN activation (otaa/abp).",
	              cmd_lrw_activation, 1, 1),

	SHELL_CMD_ARG(lrw-deveui, NULL,
	              "Get/Set LoRaWAN DevEUI (16 hex digits).",
	              cmd_lrw_deveui, 1, 1),

	SHELL_CMD_ARG(lrw-joineui, NULL,
	              "Get/Set LoRaWAN JoinEUI (16 hex digits).",
	              cmd_lrw_joineui, 1, 1),

	SHELL_CMD_ARG(lrw-nwkkey, NULL,
	              "Get/Set LoRaWAN NwkKey (32 hex digits).",
	              cmd_lrw_nwkkey, 1, 1),

	SHELL_CMD_ARG(lrw-appkey, NULL,
	              "Get/Set LoRaWAN AppKey (32 hex digits).",
	              cmd_lrw_appkey, 1, 1),

	SHELL_CMD_ARG(lrw-devaddr, NULL,
	              "Get/Set LoRaWAN DevAddr (8 hex digits).",
	              cmd_lrw_devaddr, 1, 1),

	SHELL_CMD_ARG(lrw-nwkskey, NULL,
	              "Get/Set LoRaWAN NwkSKey (32 hexadecimal digits).",
	              cmd_lrw_nwkskey, 1, 1),

	SHELL_CMD_ARG(lrw-appskey, NULL,
	              "Get/Set LoRaWAN AppSKey (32 hexadecimal digits).",
	              cmd_lrw_appskey, 1, 1),

	SHELL_CMD_ARG(alarm-temperature-enabled, NULL,
	              "Get/Set temperature alarm enabled (true/false).",
	              cmd_alarm_temperature_enabled, 1, 1),

	SHELL_CMD_ARG(alarm-temperature-lo, NULL,
	              "Get/Set temperature low threshold (-30 to 70 deg. C).",
	              cmd_alarm_temperature_lo, 1, 1),

	SHELL_CMD_ARG(alarm-temperature-hi, NULL,
	              "Get/Set temperature high threshold (-30 to 70 deg. C).",
	              cmd_alarm_temperature_hi, 1, 1),

	SHELL_CMD_ARG(alarm-temperature-hst, NULL,
	              "Get/Set T1 temperature hysteresis (0 to 5 deg. C).",
	              cmd_alarm_temperature_hst, 1, 1),

	SHELL_CMD_ARG(alarm-humidity-enabled, NULL,
	              "Get/Set humidity alarm enabled (true/false).",
	              cmd_alarm_humidity_enabled, 1, 1),

	SHELL_CMD_ARG(alarm-humidity-lo, NULL,
	              "Get/Set humidity low threshold (0 to 100 %).",
	              cmd_alarm_humidity_lo, 1, 1),

	SHELL_CMD_ARG(alarm-humidity-hi, NULL,
	              "Get/Set humidity high threshold (0 to 100 %).",
	              cmd_alarm_humidity_hi, 1, 1),

	SHELL_CMD_ARG(alarm-humidity-hst, NULL,
	              "Get/Set humidity hysteresis (0 to 20 %).",
	              cmd_alarm_humidity_hst, 1, 1),

	SHELL_CMD_ARG(alarm-pressure-enabled, NULL,
	              "Get/Set pressure alarm enabled (true/false).",
	              cmd_alarm_pressure_enabled, 1, 1),

	SHELL_CMD_ARG(alarm-pressure-lo, NULL,
	              "Get/Set pressure low threshold (500 to 1200 hPa).",
	              cmd_alarm_pressure_lo, 1, 1),

	SHELL_CMD_ARG(alarm-pressure-hi, NULL,
	              "Get/Set pressure high threshold (500 to 1200 hPa).",
	              cmd_alarm_pressure_hi, 1, 1),

	SHELL_CMD_ARG(alarm-pressure-hst, NULL,
	              "Get/Set pressure hysteresis (0 to 50 hPa).",
	              cmd_alarm_pressure_hst, 1, 1),

	SHELL_CMD_ARG(alarm-t1-temperature-enabled, NULL,
	              "Get/Set T1 temperature alarm enabled (true/false).",
	              cmd_alarm_t1_temperature_enabled, 1, 1),

	SHELL_CMD_ARG(alarm-t1-temperature-lo, NULL,
	              "Get/Set T1 temperature low threshold (-30 to 70 deg. C).",
	              cmd_alarm_t1_temperature_lo, 1, 1),

	SHELL_CMD_ARG(alarm-t1-temperature-hi, NULL,
	              "Get/Set T1 temperature high threshold (-30 to 70 deg. C).",
	              cmd_alarm_t1_temperature_hi, 1, 1),

	SHELL_CMD_ARG(alarm-t1-temperature-hst, NULL,
	              "Get/Set T1 temperature hysteresis (0 to 5 deg. C).",
	              cmd_alarm_t1_temperature_hst, 1, 1),

	SHELL_CMD_ARG(alarm-t2-temperature-enabled, NULL,
	              "Get/Set T2 temperature alarm enabled (true/false).",
	              cmd_alarm_t2_temperature_enabled, 1, 1),

	SHELL_CMD_ARG(alarm-t2-temperature-lo, NULL,
	              "Get/Set T2 temperature low threshold (-30 to 70 deg. C).",
	              cmd_alarm_t2_temperature_lo, 1, 1),

	SHELL_CMD_ARG(alarm-t2-temperature-hi, NULL,
	              "Get/Set T2 temperature high threshold (-30 to 70 deg. C).",
	              cmd_alarm_t2_temperature_hi, 1, 1),

	SHELL_CMD_ARG(alarm-t2-temperature-hst, NULL,
	              "Get/Set T2 temperature hysteresis (0 to 5 deg. C).",
	              cmd_alarm_t2_temperature_hst, 1, 1),

	SHELL_CMD_ARG(hall-left-counter, NULL,
	              "Get/Set hall left switch counter enabled (true/false).",
	              cmd_hall_left_counter, 1, 1),

	SHELL_CMD_ARG(hall-left-notify-act, NULL,
	              "Get/Set hall left switch notify on activation (true/false).",
	              cmd_hall_left_notify_act, 1, 1),

	SHELL_CMD_ARG(hall-left-notify-deact, NULL,
	              "Get/Set hall left switch notify on deactivation (true/false).",
	              cmd_hall_left_notify_deact, 1, 1),

	SHELL_CMD_ARG(hall-right-counter, NULL,
	              "Get/Set hall right switch counter enabled (true/false).",
	              cmd_hall_right_counter, 1, 1),

	SHELL_CMD_ARG(hall-right-notify-act, NULL,
	              "Get/Set hall right switch notify on activation (true/false).",
	              cmd_hall_right_notify_act, 1, 1),

	SHELL_CMD_ARG(hall-right-notify-deact, NULL,
	              "Get/Set hall right switch notify on deactivation (true/false).",
	              cmd_hall_right_notify_deact, 1, 1),

	SHELL_CMD_ARG(input-a-counter, NULL,
	              "Get/Set input A counter enabled (true/false).",
	              cmd_input_a_counter, 1, 1),

	SHELL_CMD_ARG(input-a-notify-act, NULL,
	              "Get/Set input A notify on activation (true/false).",
	              cmd_input_a_notify_act, 1, 1),

	SHELL_CMD_ARG(input-a-notify-deact, NULL,
	              "Get/Set input A notify on deactivation (true/false).",
	              cmd_input_a_notify_deact, 1, 1),

	SHELL_CMD_ARG(input-b-counter, NULL,
	              "Get/Set input B counter enabled (true/false).",
	              cmd_input_b_counter, 1, 1),

	SHELL_CMD_ARG(input-b-notify-act, NULL,
	              "Get/Set input B notify on activation (true/false).",
	              cmd_input_b_notify_act, 1, 1),

	SHELL_CMD_ARG(input-b-notify-deact, NULL,
	              "Get/Set input B notify on deactivation (true/false).",
	              cmd_input_b_notify_deact, 1, 1),

	SHELL_CMD_ARG(corr-temperature, NULL,
	              "Get/Set temperature correction (range -5.0 to +5.0 deg. C).",
	              cmd_corr_temperature, 1, 1),

	SHELL_CMD_ARG(corr-t1-temperature, NULL,
	              "Get/Set T1 temperature correction (range -5.0 to +5.0 deg. C).",
	              cmd_corr_t1_temperature, 1, 1),

	SHELL_CMD_ARG(corr-t2-temperature, NULL,
	              "Get/Set T2 temperature correction (range -5.0 to +5.0 deg. C).",
	              cmd_corr_t2_temperature, 1, 1),

	SHELL_CMD_ARG(cap-hall-left, NULL,
	              "Get/Set hall left capability (true/false).",
	              cmd_cap_hall_left, 1, 1),

	SHELL_CMD_ARG(cap-hall-right, NULL,
	              "Get/Set hall right capability (true/false).",
	              cmd_cap_hall_right, 1, 1),

	SHELL_CMD_ARG(cap-input-a, NULL,
	              "Get/Set input A capability (true/false).",
	              cmd_cap_input_a, 1, 1),

	SHELL_CMD_ARG(cap-input-b, NULL,
	              "Get/Set input B capability (true/false).",
	              cmd_cap_input_b, 1, 1),

	SHELL_CMD_ARG(cap-light-sensor, NULL,
	              "Get/Set light sensor capability (true/false).",
	              cmd_cap_light_sensor, 1, 1),

	SHELL_CMD_ARG(cap-barometer, NULL,
	              "Get/Set barometer capability (true/false).",
	              cmd_cap_barometer, 1, 1),

	SHELL_CMD_ARG(cap-pir-detector, NULL,
	              "Get/Set PIR detector capability (true/false).",
	              cmd_cap_pir_detector, 1, 1),

	SHELL_CMD_ARG(cap-1w-thermometer, NULL,
	              "Get/Set 1-wire thermometer capability (true/false).",
	              cmd_cap_1w_thermometer, 1, 1),

	SHELL_CMD_ARG(cap-1w-machine-probe, NULL,
	              "Get/Set 1-wire machine probe capability (true/false).",
	              cmd_cap_1w_machine_probe, 1, 1),

	SHELL_SUBCMD_SET_END
);

/* clang-format on */

SHELL_CMD_REGISTER(config, &sub_config, "Configuration commands.", print_help);

#endif /* defined(CONFIG_SHELL) */

struct app_config *app_config(void)
{
	return &m_app_config;
}

static int app_config_init(void)
{
	int ret;

	ret = settings_subsys_init();
	if (ret) {
		LOG_ERR("Call `settings_subsys_init` failed: %d", ret);
		return ret;
	}

	static struct settings_handler sh = {
		.name = SETTINGS_PFX,
		.h_set = h_set,
		.h_commit = h_commit,
		.h_export = h_export,
	};

	ret = settings_register(&sh);
	if (ret) {
		LOG_ERR("Call `settings_register` failed: %d", ret);
		return ret;
	}

	ret = settings_load_subtree(SETTINGS_PFX);
	if (ret) {
		LOG_ERR("Call `settings_load_subtree` failed: %d", ret);
		return ret;
	}

	return 0;
}

SYS_INIT(app_config_init, APPLICATION, 0);
