syntax = "proto3";

message NfcConfigMessage {
    optional bool factory = 1;

    optional string secret_key = 2;
    optional uint32 serial_number = 3;
    optional uint32 nonce_counter = 4;

    optional Lorawan lorawan = 5;
    optional Application application = 6;

    message Lorawan {
        enum Region {
            EU868 = 0;
            US915 = 1;
            AU915 = 2;
        }

        enum Activation {
            OTAA = 0;
            ABP = 1;
        }

        enum Network {
            PUBLIC = 0;
            PRIVATE = 1;
        }

        optional Region region = 1;
        optional Network network = 2;
        optional bool adr = 3;
        optional Activation activation = 4;
        optional string deveui = 5;
        optional string joineui = 6;
        optional string nwkkey = 7;
        optional string appkey = 8;
        optional string devaddr = 9;
        optional string nwkskey = 10;
        optional string appskey = 11;
        optional uint32 sub_band = 12;
    }

    message Application {
        optional bool calibration = 1;
        optional uint32 interval_sample = 2;
        optional uint32 interval_aggreg = 3;
        optional uint32 interval_report = 4;
        optional bool alarm_temperature_enabled = 5;
        optional float alarm_temperature_lo = 6;
        optional float alarm_temperature_hi = 7;
        optional float alarm_temperature_hst = 8;
        optional bool alarm_humidity_enabled = 9;
        optional float alarm_humidity_lo = 10;
        optional float alarm_humidity_hi = 11;
        optional float alarm_humidity_hst = 12;
        optional bool alarm_pressure_enabled = 13;
        optional float alarm_pressure_lo = 14;
        optional float alarm_pressure_hi = 15;
        optional float alarm_pressure_hst = 16;
        optional bool alarm_t1_temperature_enabled = 17;
        optional float alarm_t1_temperature_lo = 18;
        optional float alarm_t1_temperature_hi = 19;
        optional float alarm_t1_temperature_hst = 20;
        optional bool alarm_t2_temperature_enabled = 21;
        optional float alarm_t2_temperature_lo = 22;
        optional float alarm_t2_temperature_hi = 23;
        optional float alarm_t2_temperature_hst = 24;
        optional bool hall_left_counter = 25;
        optional bool hall_left_notify_act = 26;
        optional bool hall_left_notify_deact = 27;
        optional bool hall_right_counter = 28;
        optional bool hall_right_notify_act = 29;
        optional bool hall_right_notify_deact = 30;
        optional bool input_a_counter = 31;
        optional bool input_a_notify_act = 32;
        optional bool input_a_notify_deact = 33;
        optional bool input_b_counter = 34;
        optional bool input_b_notify_act = 35;
        optional bool input_b_notify_deact = 36;
        optional float corr_temperature = 37;
        optional float corr_t1_temperature = 38;
        optional float corr_t2_temperature = 39;
        optional bool cap_hall_left = 40;
        optional bool cap_hall_right = 41;
        optional bool cap_input_a = 42;
        optional bool cap_input_b = 43;
        optional bool cap_light_sensor = 44;
        optional bool cap_barometer = 45;
        optional bool cap_pir_detector = 46;
        optional bool cap_1w_thermometer = 47;
        optional bool cap_1w_machine_probe = 48;
    }
}
